from typing import Protocol, runtime_checkable


@runtime_checkable
class CampaignRepository(Protocol):
    def reset(self) -> None: ...

    def list(self) -> list[dict]: ...

    def get(self, campaign_id: str) -> dict | None: ...

    def get_by_name(self, name: str) -> dict | None: ...

    def create(self, data: dict) -> dict: ...

    def update(self, campaign_id: str, data: dict) -> dict: ...


@runtime_checkable
class FunnelRepository(Protocol):
    def reset(self) -> None: ...

    def list_events(self) -> list[dict]: ...

    def create_many(self, events: list[dict]) -> list[dict]: ...
